import { Inter } from "next/font/google";
import SideBar from "./Layouts/SideBar";
import './globals.css'
import './style/style.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar/>
        {children}</body>
    </html>
  );
}
